export default {
	REQUEST_ITEMS: "REQUEST_ITEMS",
	RECEIVE_ITEMS: "RECEIVE_ITEMS",
	RECEIVE_ITEMS_ERROR: "RECEIVE_ITEMS_ERROR",
	SET_CARD_SELECTED: "SET_CARD_SELECTED",
	SET_FILTER_STRING: "SET_FILTER_STRING"
};
